routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Pokemons;

Route::get('/', function () {
    return redirect('/pokemons');
});
Route::resource('pokemons', 'PokemonsController');
Route::resource('fights', 'FightsController');
Route::resource('trainers', 'TrainersController');
Route::resource('teams', 'TrainersPokemonsController');

resources/views/custom-pagination.blade.php
<?php
// config
$link_limit = 7; // maximum number of links (a little bit inaccurate, but will be ok for now)
?>

@if ($paginator->lastPage() > 1)
    <ul class="pagination">
        <li class="{{ ($paginator->currentPage() == 1) ? ' disabled' : '' }}">
            <a href="{{ $paginator->url(1) }}"><<</a>
         </li>
        @for ($i = 1; $i <= $paginator->lastPage(); $i++)
            <?php
            $half_total_links = floor($link_limit / 2);
            $from = $paginator->currentPage() - $half_total_links;
            $to = $paginator->currentPage() + $half_total_links;
            if ($paginator->currentPage() < $half_total_links) {
               $to += $half_total_links - $paginator->currentPage();
            }
            if ($paginator->lastPage() - $paginator->currentPage() < $half_total_links) {
                $from -= $half_total_links - ($paginator->lastPage() - $paginator->currentPage()) - 1;
            }
            ?>
            @if ($from < $i && $i < $to)
                <li class="{{ ($paginator->currentPage() == $i) ? ' active' : '' }}">
                    <a href="{{ $paginator->url($i) }}">{{ $i }}</a>
                </li>
            @endif
        @endfor
        <li class="{{ ($paginator->currentPage() == $paginator->lastPage()) ? ' disabled' : '' }}">
            <a href="{{ $paginator->url($paginator->lastPage()) }}">>></a>
        </li>
    </ul>
@endif

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ env('APP_NAME') }}</title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <ul id="dropdown_pkmn" class="dropdown-content">
        <li><a href="{{route('pokemons.index')}}">Pokémons</a></li>
        <li class="divider"></li>
        <li><a href="{{route('pokemons.create')}}">Nouveau pokémon</a></li>
    </ul>
    <ul id="dropdown_trainers" class="dropdown-content">
        <li><a href="{{route('trainers.index')}}">Dresseurs</a></li>
        <li class="divider"></li>
        <li><a href="{{route('trainers.create')}}">Nouveau dresseur</a></li>
    </ul>
    <ul id="dropdown_teams" class="dropdown-content">
        <li><a href="{{route('teams.index')}}">Equipes</a></li>
        <li class="divider"></li>
        <li><a href="{{route('teams.create')}}">Nouvelle equipe</a></li>
    </ul>
    <ul id="dropdown_fights" class="dropdown-content">
        <li><a href="{{route('fights.index')}}">Combats</a></li>
        <li class="divider"></li>
        <li><a href="{{route('fights.create')}}">Nouveau combat</a></li>
    </ul>

    <nav class="light-blue lighten-1" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{{route('pokemons.index')}}" class="brand-logo">Pokéapp</a>
            <ul class="right hide-on-med-and-down">
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown_pkmn">Pokémons<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown_trainers">Dresseurs<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown_teams">Equipes<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown_fights">Combats<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>

            <ul id="nav-mobile" class="sidenav">
                <li><a href="{{route('pokemons.index')}}">Pokémons</a></li>
                <li><a href="{{route('pokemons.create')}}">Nouveau pokémon</a></li>
                <li class="divider"></li>
                <li><a href="{{route('trainers.index')}}">Dresseurs</a></li>
                <li><a href="{{route('trainers.create')}}">Nouveau dresseur</a></li>
                <li class="divider"></li>
                <li><a href="{{route('teams.index')}}">Equipes</a></li>
                <li><a href="{{route('teams.create')}}">Nouvelle équipe</a></li>
                <li class="divider"></li>
                <li><a href="{{route('fights.index')}}">Combats</a></li>
                <li><a href="{{route('fights.create')}}">Nouveau combat</a></li>

            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <div class="container">
        @yield('main')
    </div>
    <script src="{{ asset('js/app.js') }}" type="text/js"></script>

    <!-- Materialize -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        $(document).ready(function() {
        
            $('.sidenav').sidenav();  
            $("li .dropdown-trigger").dropdown({
                'hover':true,
                'coverTrigger':false
            });
        });
    </script>
</body>

</html>