routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Pokemons;

Route::get('/', function () {
    return redirect('/pokemons');
});
Route::resource('pokemons', 'PokemonsController');
Route::resource('fights', 'FightsController');
Route::resource('trainers', 'TrainersController');
Route::resource('teams', 'TrainersPokemonsController');

app/Pokemons.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pokemons extends Model
{
    protected $fillable = [
        'name',
        'pokedex_id',
        'hp',
        'atk',
        'def',
        'spe',
    ];




}

app/Http/Controllers/PokemonsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePokemons;
use App\Http\Requests\UpdatePokemons;
use App\Pokemons;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class PokemonsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param string $sort = 'pokedex_id'
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pokemons = DB::table('pokemons')->paginate(24);
        return view('pokemons.index', compact('pokemons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pokemons.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePokemons $request)
    {
        $request->validated();
        $pokemon = new Pokemons([
            'name' => $request->get('name'),
            'pokedex_id' => $request->get('pokedex_id'),
            'hp' => $request->get('hp'),
            'atk' => $request->get('atk'),
            'def' => $request->get('def'),
            'spe' => $request->get('spe'),
        ]);
        $pokemon->save();
        return redirect('/pokemons')->with('success', 'Un nouveau pokémon fait son apparition !');
    }

     /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pokemon = Pokemons::find($id);
        return view('pokemons.edit', compact('pokemon'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePokemons $request,$id)
    {
        $request->validated($id);

        $pokemon = Pokemons::find($id);
        $pokemon->name = $request->get('name');
        $pokemon->pokedex_id = $request->get('pokedex_id');
        $pokemon->hp = $request->get('hp');
        $pokemon->atk = $request->get('atk');
        $pokemon->def = $request->get('def');
        $pokemon->spe = $request->get('spe');
        $pokemon->save();

        return redirect('/pokemons')->with('success', 'Pokemon mis à jour !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pokemon = Pokemons::find($id);
        $pokemon->delete();

        return redirect('/pokemons')->with('success', 'Pokémon supprimé !');
    }
}

resources/views/pokemons/create.blade.php
@extends('template')

@section('main')
<div class="row">
    <div class="col s8 offset-s2">
        <h1 class="center-align">Ajouter un pokémon</h1>
        <div>
            @if ($errors->any())
            <div class="red darken-1">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('pokemons.store') }}">
                @csrf
                <div class="input-field col s12">
                    <label for="name">Nom</label>
                    <input type="text" class="form-control" name="name" />
                </div>

                <div class="input-field col s12 l6">
                    <label for="pokedex_id">N° Pokedex</label>
                    <input type="number" class="form-control" name="pokedex_id" />
                </div>

                <div class="input-field col s12 l6">
                    <label for="hp">Points de vie</label>
                    <input type="number" class="form-control" name="hp" />
                </div>
                
                <div class="input-field col s12 l4">
                    <label for="atk">Attaque</label>
                    <input type="number" class="form-control" name="atk" />
                </div>

                <div class="input-field col s12 l4">
                    <label for="def">Défense</label>
                    <input type="number" class="form-control" name="def" />
                </div>

                <div class="input-field col s12 l4">
                    <label for="spe">Vitesse</label>
                    <input type="number" class="form-control" name="spe" />
                </div>
                <div class="col l8 offset-l4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Enregistrer le pokémon
                        <i class="material-icons right">save</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pokemons/edit.blade.php
@extends('template')
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Editer un pokémon</h1>

        @if ($errors->any())
        <div class="red darken-1">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('pokemons.update', $pokemon->id) }}">
            @method('PATCH')
            @csrf
            <input type="hidden" name="id" value="{{$pokemon->id}}"/>
            <div class="input-field col s12">
                    <label for="name">Nom</label>
                    <input type="text" class="form-control" name="name" value="{{$pokemon->name}}" />
                </div>

                <div class="input-field col s12 l6">
                    <label for="pokedex_id">N° Pokedex</label>
                    <input type="number" class="form-control" name="pokedex_id" value="{{$pokemon->pokedex_id}}"/>
                </div>

                <div class="input-field col s12 l6">
                    <label for="hp">Points de vie</label>
                    <input type="number" class="form-control" name="hp" value="{{$pokemon->hp}}"/>
                </div>
                
                <div class="input-field col s12 l4">
                    <label for="atk">Attaque</label>
                    <input type="number" class="form-control" name="atk" value="{{$pokemon->atk}}">
                </div>

                <div class="input-field col s12 l4">
                    <label for="def">Défense</label>
                    <input type="number" class="form-control" name="def" value="{{$pokemon->def}}"/>
                </div>

                <div class="input-field col s12 l4">
                    <label for="spe">Vitesse</label>
                    <input type="number" class="form-control" name="spe" value="{{$pokemon->spe}}"/>
                </div>

                <div class="col l8 offset-l4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Modifier le pokémon
                        <i class="material-icons right">save</i>
                    </button>
                </div>

        </form>
    </div>
</div>
@endsection

resources/views/pokemons/index.blade.php
@extends('template')

@section('main')
<div class="row">
    <div class="col s12">
        <div class="col s12">

            @if(session()->get('success'))
            <div class="card panel green darken-1">
                {{ session()->get('success') }}
            </div>
            @endif
        </div>
        <h1 class="display-3">Pokémons</h1>

        <form action="{{ route('pokemons.create')}}" method="post">
            @csrf
            @method('GET')
            <button type="submit" class="waves-effect waves-light btn" id="add">Ajouter un pokémon</button>
        </form>

        <div class="crud-flexbox">
            @foreach($pokemons as $pokemon)


            <div class="card col s12 m4 l4 hoverable" id="{{$pokemon->id}}">
                <div class="card-image">
                    <img class="responsive-img col s6 offset-s3">
                </div>
                <div class="card-content">
                    <span class="card-title center-align">{{$pokemon->name}}</span>
                    <ul>
                        <li class="center-align">N° Pokedex : {{$pokemon->pokedex_id}}</li>
                        <li class="center-align">PV : {{$pokemon->hp}}</li>
                        <li class="center-align">Attaque : {{$pokemon->atk}}</li>
                        <li class="center-align">Défense : {{$pokemon->def}}</li>
                        <li class="center-align">Vitesse :{{$pokemon->spe}} </li>
                    </ul>
                </div>
                <div class="card-action">
                    <div class="col s6 center-align">
                        <a href="{{ route('pokemons.edit',$pokemon->id)}}" class="waves-effect waves-light btn"><i class="material-icons">create</i></a>
                    </div>
                    <div class="col s6 center-align">
                        <form action="{{ route('pokemons.destroy', $pokemon->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="waves-effect waves-light btn red darken-1"><i class="material-icons">delete</i></button>
                        </form>
                    </div>

                </div>
            </div>

            @endforeach

        </div>

        {{ $pokemons->links('custom-pagination') }}
    </div>

</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
    });


    $(document).ready(function() {
        loadSprites($('.card:first'), 0);
    });

    function loadSprites(element, i) {
        var cards = $('.card');


        $.ajax({

            type: 'GET',

            url: "https://pokeapi.co/api/v2/pokemon/" + element.attr("id"),

            success: function(response) {
                element.children(".card-image").children().attr('src', response.sprites.front_default);
                i++;
                if (i <= cards.length) {
                    loadSprites($(cards[i]), i);
                }
                
            }
        });

    }
</script>
@endsection