routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Pokemons;

Route::get('/', function () {
    return redirect('/pokemons');
});
Route::resource('pokemons', 'PokemonsController');
Route::resource('fights', 'FightsController');
Route::resource('trainers', 'TrainersController');
Route::resource('teams', 'TrainersPokemonsController');

app/Trainers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trainers extends Model
{
    protected $fillable = [
        'firstname',
        'lastname',       
    ];
}

app/Http/Controllers/TrainersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTrainers;
use App\Trainers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class TrainersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trainers = DB::table('trainers')->paginate(24);
        return view('trainers.index', compact('trainers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('trainers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTrainers $request)
    {
        $request->validated();

        $trainer = new Trainers([
            'firstname' => $request->get('firstname'),
            'lastname' => $request->get('lastname')
        ]);
        $trainer->save();
        return redirect('/trainers')->with('success', 'Un nouveau dresseur fait son apparition !');
    }

     /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trainer = Trainers::find($id);
        return view('trainers.edit', compact('trainer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTrainers $request,$id)
    {
        $request->validated();

        $trainer = Trainers::find($id);
        $trainer->firstname =  $request->get('firstname');
        $trainer->lastname = $request->get('lastname');

        $trainer->save();

        return redirect('/trainers')->with('success', 'Dresseur mis à jour !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $trainer = Trainers::find($id);
        $trainer->delete();

        return redirect('/trainers')->with('success', 'Dresseur supprimé !');
    }
}

resources/views/trainers/create.blade.php
@extends('template')

@section('main')
<div class="row">
    <div class="col s8 offset-s2">
        <h1 class="center-align">Ajouter un dresseur</h1>
        <div>
            @if ($errors->any())
            <div class="red darken-1">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
            @endif
            <form method="post" action="{{ route('trainers.store') }}">
                @csrf
                <div class="input-field col s12">
                    <label for="firstname">Prénom</label>
                    <input type="text" class="form-control" name="firstname" />
                </div>

                <div class="input-field col s12">
                    <label for="lastname">Nom</label>
                    <input type="text" class="form-control" name="lastname" />
                </div>

                <div class="col l8 offset-l4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">Enregistrer le dresseur
                        <i class="material-icons right">save</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/trainers/edit.blade.php
@extends('template')
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Editer un dresseur</h1>

        @if ($errors->any())
        <div class="red darken-1">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('trainers.update', $trainer->id) }}">
            @method('PATCH')
            @csrf

            <div class="input-field col s12">
                <label for="firstname">Prénom</label>
                <input type="text" class="form-control" name="firstname" value="{{ $trainer->firstname }}"/>
            </div>

            <div class="input-field col s12">
                <label for="lastname">Nom</label>
                <input type="text" class="form-control" name="lastname"  value="{{ $trainer->lastname }}"/>
            </div>

            <div class="col l8 offset-l4">
                <button class="btn waves-effect waves-light" type="submit" name="action">Mettre à jour le dresseur
                    <i class="material-icons right">save</i>
                </button>
            </div>

        </form>
    </div>
</div>
@endsection

resources/views/trainers/index.blade.php
@extends('template')

@section('main')
<div class="row">
    <div class="col-sm-12">
        <div class="col-sm-12">

            @if(session()->get('success'))
            <div class="card panel green darken-1">
                {{ session()->get('success') }}
            </div>
            @endif
        </div>
        <h1 class="display-3">Dresseurs</h1>

        <form action="{{ route('trainers.create')}}" method="post">
            @csrf
            @method('GET')
            <button type="submit" class="waves-effect waves-light btn" id="add">Ajouter un dresseur</button>
        </form>

        <div class="crud-flexbox" id="flex">
            @foreach($trainers as $trainer)
            <div class="card col s12 m4 l4 hoverable left">
                <div class="card-content">
                    <span class="card-title center-align"> {{$trainer->firstname}} {{$trainer->lastname}} </span>
                </div>
                <div class="card-action">
                    <div class="col s6 center-align">
                        <a href="{{ route('trainers.edit',$trainer->id)}}" class="waves-effect waves-light btn"><i class="material-icons">create</i></a>
                    </div>
                    <div class="col s6 center-align">
                        <form action="{{ route('trainers.destroy', $trainer->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="waves-effect waves-light btn red darken-1"><i class="material-icons">delete</i></button>
                        </form>
                    </div>

                </div>

            </div>
            @endforeach
        </div>
        {{ $trainers->links('custom-pagination') }}
        <div>
        </div>
        @endsection